from config import (
    CLAUDE_API_KEY,
    CLAUDE_MODEL,
    CLAUDE_URL,
    LLM_TEMPERATURE,
    OLLAMA_HOST,
    OLLAMA_MODEL,
    USE_OLLAMA,
)
from langchain_community.llms import Ollama
from langchain_anthropic import ChatAnthropic
from langchain_core.documents import Document
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
import logging
from templates import SYSTEM_TEXT_TEMPLATE

logger = logging.getLogger(__name__)


def create_llm():
    """Create the configured LLM without making a network request."""
    if USE_OLLAMA:
        return Ollama(
            model=OLLAMA_MODEL,
            base_url=OLLAMA_HOST,
            temperature=LLM_TEMPERATURE,
        )

    if not CLAUDE_API_KEY:
        raise ValueError("CLAUDE_API_KEY is required when USE_OLLAMA=false")

    options = {
        "model": CLAUDE_MODEL,
        "api_key": CLAUDE_API_KEY,
        "temperature": LLM_TEMPERATURE,
        "max_tokens": 2048,
    }
    if CLAUDE_URL:
        options["base_url"] = CLAUDE_URL.rstrip("/")

    return ChatAnthropic(**options)


class Generator:
    """
    LLM-based answer generator for RAG system.

    Takes retrieved context documents and a user query, then generates
    a natural language answer using an LLM (Claude API or Ollama).
    """

    def __init__(self):
        self.llm = create_llm()

        self.system_template = SYSTEM_TEXT_TEMPLATE
        self.doc_prompt = PromptTemplate.from_template(
            "{law_id} | {chapter} | {article}\n{page_content}"
        )

        self.qa_prompt = ChatPromptTemplate.from_messages(
            [("system", self.system_template), ("human", "{question}")]
        )

        self.combine_docs_chain = create_stuff_documents_chain(
            self.llm, self.qa_prompt, document_prompt=self.doc_prompt
        )

        model = "Ollama" if USE_OLLAMA else CLAUDE_MODEL
        print(f"Generator initialized: {model} (temperature={LLM_TEMPERATURE})")

    def generate(
        self,
        query: str,
        documents: list[Document],
        scores: list[float] | None = None,
        include_sources: bool = True,
    ) -> dict:
        """
        Generate an answer to the query using retrieved documents as context.

        Args:
            query: User's question
            documents: Retrieved context documents (from retriever)
            scores: Relevance scores for each document, aligned with `documents`
            include_sources: Whether to include source documents in response

        Returns:
            dict with keys:
                - answer (str): Generated answer
                - sources (list[dict]): Source documents with metadata (if include_sources=True)
        """

        answer = self.combine_docs_chain.invoke({"question": query, "context": documents})
        # ChatAnthropic returns AIMessage; Ollama returns a plain string
        answer = getattr(answer, "content", answer).strip()

        logger.info("query=%r sources=%d answer_len=%d", query, len(documents), len(answer))

        response: dict = {"answer": answer}

        if include_sources:
            response["sources"] = self.format_sources(documents, scores)

        return response

    def generate_stream(self, query: str, documents: list[Document]):
        """
        Generate an answer with streaming support.

        Yields answer chunks as they're generated by the LLM, allowing
        for real-time streaming to the client.

        Args:
            query: User's question
            documents: Retrieved context documents (from retriever)

        Yields:
            str: Chunks of the generated answer as they arrive
        """

        for chunk in self.combine_docs_chain.stream({"question": query, "context": documents}):
            yield chunk

    def format_sources(
        self, documents: list[Document], scores: list[float] | None = None
    ) -> list[dict]:
        sources = []
        for idx, doc in enumerate(documents, 1):
            source_dict = {
                "rank": idx,
                "source": doc.metadata.get("source", "unknown"),
                "snippet": doc.page_content,
            }
            if scores and idx - 1 < len(scores):
                source_dict["score"] = round(scores[idx - 1], 4)
            sources.append(source_dict)
        return sources
