from config import (
    CLAUDE_API_KEY,
    CLAUDE_MODEL,
    CLAUDE_URL,
    LLM_TEMPERATURE,
    OLLAMA_HOST,
    OLLAMA_MODEL,
    USE_OLLAMA,
)
from langchain_community.llms import Ollama
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from typing import List, Dict
from templates import SYSTEM_TEXT_TEMPLATE


class Generator:
    """
    LLM-based answer generator for RAG system.

    Takes retrieved context documents and a user query, then generates
    a natural language answer using an LLM (via Ollama).
    """

    def __init__(self):
        if USE_OLLAMA:
            self.llm = Ollama(model=OLLAMA_MODEL, base_url=OLLAMA_HOST, temperature=LLM_TEMPERATURE)
        else:
            self.llm = ChatAnthropic(
                model=CLAUDE_MODEL,
                base_url=f"{CLAUDE_URL}/anthropic",
                api_key=CLAUDE_API_KEY,
                temperature=LLM_TEMPERATURE,
                max_tokens=2048,
            )

        self.system_template = SYSTEM_TEXT_TEMPLATE
        self.doc_prompt = PromptTemplate.from_template(
            "--- Document (Source: {source}) ---\n{page_content}\n--- END OF DOCUMENT ---"
        )

        self.qa_prompt = ChatPromptTemplate.from_messages(
            [("system", self.system_template), ("human", "{question}")]
        )

        self.combine_docs_chain = create_stuff_documents_chain(
            self.llm, self.qa_prompt, document_prompt=self.doc_prompt
        )

        model = "Ollama" if USE_OLLAMA == True else CLAUDE_MODEL
        print(f"Generator initialized: {model} (temperature={LLM_TEMPERATURE})")

    def generate(
        self, query: str, documents: List, scores: List[float] = None, include_sources: bool = True
    ) -> Dict:
        """
        Generate an answer to the query using retrieved documents as context.

        Args:
            query (str): User's question
            documents (list[Document]): Retrieved context documents (from retriever)
            scores (list[float], optional): Relevance scores for each document
            include_sources (bool): Whether to include source documents in response

        Returns:
            dict: Response containing:
                - answer (str): Generated answer
                - sources (list[dict]): Source documents with metadata (if include_sources=True)

        Example:
            >>> generator = Generator()
            >>> docs = [...]  # Retrieved documents
            >>> result = generator.generate("How do I set Pod limits?", docs)
            >>> print(result['answer'])
        """

        answer = self.combine_docs_chain.invoke({"question": query, "context": documents})

        response = {
            "answer": answer.strip(),
        }

        if include_sources:
            response["sources"] = self._format_sources(documents, scores)

        return response

    def generate_stream(self, query: str, documents: List):
        """
        Generate an answer with streaming support.

        Yields answer chunks as they're generated by the LLM, allowing
        for real-time streaming to the client.

        Args:
            query (str): User's question
            documents (list[Document]): Retrieved context documents (from retriever)

        Yields:
            str: Chunks of the generated answer as they arrive

        Example:
            >>> generator = Generator()
            >>> docs = [...]  # Retrieved documents
            >>> for chunk in generator.generate_stream("How do I set Pod limits?", docs):
            >>>     print(chunk, end="", flush=True)
        """

        for chunk in self.combine_docs_chain.stream({"question": query, "context": documents}):
            yield chunk

    def _format_sources(self, documents: List, scores: List[float] = None) -> List[Dict]:
        """
        Format documents as source references for the response.

        Args:
            documents (list[Document]): Retrieved documents
            scores (list[float], optional): Relevance scores for each document

        Returns:
            list[dict]: List of source dictionaries with metadata
        """
        sources = []

        for idx, doc in enumerate(documents, 1):
            source_dict = {
                "rank": idx,
                "source": doc.metadata.get("source", "unknown"),
                # "snippet": doc.page_content[:200] + "..." if len(doc.page_content) > 200 else doc.page_content
                "snippet": doc.page_content,
            }

            if scores and idx - 1 < len(scores):
                source_dict["score"] = round(scores[idx - 1], 4)

            sources.append(source_dict)

        return sources
